variable "vpc_cidr" {}
variable "pub_sub1_cidr" {}
variable "availability_zone_1" {}
variable "pub_sub2_cidr" {}
variable "availability_zone_2" {}
variable "priv_sub1_cidr" {}
variable "priv_sub2_cidr" {}
variable "all_cidr" {}
variable "key_name" {}
variable "public_key" {}
variable "private_key" {}
variable "tag-vpc" {}
variable "tag-public_subnet1" {}
variable "tag-public_subnet2" {}
variable "tag-private_subnet1" {}
variable "tag-private_subnet2" {}
variable "tag-igw" {}
variable "tag-natgw" {}
variable "tag-public_RT" {}
variable "tag-private_RT" {}
