variable "prod-tg" {}
variable "port_proxy" {}
variable "vpc_id" {}
variable "prod-alb" {}
variable "alb-SG" {}
variable "subnet1-id" {}
variable "subnet2-id" {}
variable "port_http" {}
variable "port_https" {}
variable "cert-arn" {}