variable "ami_redhat" {}
variable "instance_type" {}
variable "key-name" {}
variable "ansible-SG" {}
variable "subnetid" {}
variable "ansible-server" {}
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "stage-bash-script" {}
variable "prod-bash-script" {}
variable "stage-trigger" {}
variable "prod-trigger" {}
variable "password" {}
variable "private-key" {}
variable "nexus-ip" {}
variable "nr_license_key" {}